#ifndef T_TACSYMBOL_H
#define T_TACSYMBOL_H

enum t_tacsymbol
{

  TAC_ASSIGN_READPOL,
  TAC_ASSIGN_SHOWTAC,
  TAC_ASSIGN_HIDETAC,
  TAC_ASSIGN_SHOWCODE,
  TAC_ASSIGN_HIDECODE,
  TAC_ASSIGN_SHOWSTATEVM,
  TAC_ASSIGN_HIDESTATEVM,		
  TAC_ASSIGN_SUBINSTRUCTIONS,	
  TAC_ASSIGN_INSTRUCTIONS,
  TAC_ASSIGN_PROG_JUMP,
  TAC_ASSIGN_STARTCALL,
  TAC_ASSIGN_CALL,
  TAC_ASSIGN_FUNCTION,
  TAC_ASSIGN_METHOD,
  TAC_ASSIGN_CLASS,
  TAC_ASSIGN_ENDCLASS,
  TAC_ASSIGN_RETURN,
  TAC_ASSIGN_RETURN_WITHOUT_VALUE,
  TAC_ASSIGN_DECLR_ARRAY,
  TAC_ASSIGN_DECLR,
  TAC_ASSIGN_PRINT,
  TAC_ASSIGN_EXIT,
  TAC_ASSIGNV, 
  TAC_ASSIGNL, 
  TAC_ASSIGNC,
  TAC_ASSIGNS,
  TAC_ASSIGNCA,
  TAC_ASSIGN_ADD,
  TAC_ASSIGN_SUB,
  TAC_ASSIGN_DIV,
  TAC_ASSIGN_MUL,
  TAC_ASSIGN_INF,
  TAC_ASSIGN_SUP,
  TAC_ASSIGN_INFEQUAL,
  TAC_ASSIGN_SUPEQUAL,
  TAC_ASSIGN_TIMER,
  TAC_ASSIGN_PARAM,
  TAC_ASSIGN_IF, // 32
  TAC_ASSIGN_IFTRUE, // 33
  TAC_ASSIGN_ELSEIF, // 34
  TAC_ASSIGN_ELSE, // 35
  TAC_ASSIGN_ENDIF, // 36
  TAC_ASSIGN_ENDELSEIF, // 37
  TAC_ASSIGN_ENDELSE, // 38
  TAC_ASSIGN_NOELSE, // 39
  TAC_ASSIGN_STARTFOR, // 40
  TAC_ASSIGN_FOR, // 41
  TAC_ASSIGN_ENDFOR,// 42
  TAC_ASSIGN_ARRAY, // 43
  TAC_ASSIGN_FACTOR_ARRAY, // 44
  TAC_ASSIGN_NULL // 45
};

#endif

